config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "movie_sessions#index"

  get 'my_tickets', to: 'users#tickets'
  post 'webhooks', to: 'webhooks#create'

  resources :movie_sessions do
    get :swap, on: :member
    post :payment, on: :member
  end

  namespace :admin do
    resources :movies do
      post :search, on: :collection
      post 'create_with_tmdb/:external_id', on: :collection, as: :create_with_tmdb, action: :create_with_tmdb
    end

    resources :users, only: %i[index update], path: :staff do
      post 'add', on: :collection
    end

    resources :halls, except: %i[show new] do
      post :build_chart, on: :collection
    end

    resources :sessions, only: %i[index create destroy update] do
      get :tickets, on: :member
      post :book, on: :member
    end
  end
end

app/controllers/admin/movies_controller.rb
module Admin
  class MoviesController < Admin::BaseController
    before_action -> { authorize(:movie) }
    before_action :load_movies, only: %i[index new search create_with_tmdb]
    before_action :load_tmdb_movies, only: %i[new create_with_tmdb]
    before_action :load_movie, only: %i[edit update destroy]

    def index; end

    def new
      @movie = Movie.new
    end

    def create
      @movie = Movie.new(movie_params)
      if @movie.save
        flash[:success] = 'The movie has been added to our collection.'
        redirect_to admin_movies_path
      else
        load_movies
        load_tmdb_movies
        render :new, status: :unprocessable_entity
      end
    end

    def create_with_tmdb
      @movie = TmdbConstructionService.call(external_id: params[:external_id])
      if @movie.save
        @movie = Movie.new
        flash.now[:success] = 'The movie has been copied to our collection.'
        render :new, status: :created
      else
        cookies[:active_movie_tab] = 'Add Manually'
        flash.now[:danger] = 'All required fields must be filled'
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @movie.update(movie_params)
        flash[:success] = 'The movie has been updated.'
        redirect_to admin_movies_path
      else
        flash.now[:danger] = 'Something went wrong.'
        render :edit
      end
    end

    def search
      @search_list = TmdbApiService.call(action: :search, opts: { query: params[:query] }).dig('results')
    end

    def destroy
      if @movie.destroy
        flash[:success] = 'Movie successfully deleted'
      else
        flash[:danger] = @movie.errors.full_messages.join('. ')
      end
      redirect_to request.referer || admin_movies_path
    end

    private

    def movie_params
      params.require(:movie).permit(:title, :description, :duration, :release_date, :poster, countries: [], directors: [], actors: [], genre: [])
    end

    def load_movies
      @movies ||= Movie.all
    end

    def load_tmdb_movies
      @now_playing_list = TmdbApiService.call(action: :now_playing).dig('results')
      @upcoming_list = TmdbApiService.call(action: :upcoming).dig('results')
    end

    def load_movie
      @movie = Movie.find(params[:id])
    end
  end
end

app/views/admin/movies/_card.html.erb
<div class="col">
  <div class="card shadow-sm">
    <% if movie['poster_path'].present? %>
      <img src="<%= "#{Settings.tmdb.img_url}#{Settings.tmdb.img_path}#{movie['poster_path']}" %>" class="card-img-top">
    <% elsif movie.is_a?(Movie) && movie.poster.present? %>
      <%= image_tag url_for(movie.poster), class: 'card-img-top' %>
    <% else %>
      <%= image_tag image_path('no-image.jpg'), class: 'card-img-top' %>
    <% end %>
    <div class="card-body fixed-card-body">
      <h5 class="card-title text-clamp text-clamp-1"><%= movie['title'] %></h5>
      <% if movie['release_date'].present? %>
        <% if movie['release_date'].is_a?(Date) %>
          <time><%= movie['release_date'].strftime("%b %d, %Y") %></time>
        <% else %>
          <time><%= DateTime.parse(movie['release_date']).strftime("%b %d, %Y") %></time>
        <% end %>
      <% else %>
        <span>No data</span>
      <% end %>
      <p class="card-text text-clamp text-clamp-4"><%= movie['overview'] || movie.description %></p>
    </div>
    <div class="card-footer border-0 bg-white text-end">
      <% target_movie = movie.is_a?(Movie) ? movie : @movies.find { |x| x.external_id == movie['id'] } %>
      <% if target_movie %>
        <%= link_to 'Edit', edit_admin_movie_path(target_movie), class: 'btn btn-outline-dark' if policy(:movie).edit? %>
        <% if policy(:movie).destroy? %>
          <%= link_to 'Remove', admin_movie_path(target_movie), class: 'btn btn-outline-dark',
                      data: { turbo_method: :delete, turbo_confirm: 'Are you sure? All sessions with this movie will also be deleted' } %>
        <% end %>
      <% else %>
        <%= button_to 'Add to our collection', create_with_tmdb_admin_movies_path(movie['id']), class: 'btn btn-dark' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/movies/_form.html.erb
<%= simple_form_for @movie, url: @movie.persisted? ? admin_movie_path(@movie) : admin_movies_path do |f| %>
  <div class="row justify-content-center">
    <div class="col-5">
      <h3 class="fs-3"><%= @movie.persisted? ? 'Edit Movie' : 'New Movie' %></h3>
    </div>
    <div class="col-3 text-end">
      <%= f.submit nil, class: 'btn btn-dark' %>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-12 col-lg-6"><%= f.input :title %></div>
    <div class="col-12 col-lg-2"><%= f.input :duration %></div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-12 col-lg-8"><%= f.input :description, as: :text, input_html: { rows: 3 } %></div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-12 col-lg-4"><%= f.input :release_date, as: :date, start_year: 1900 %></div>
    <div class="col-12 col-lg-4"><%= f.input :poster %></div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-6 col-lg-2"><%= f.input :genre, as: :array %></div>
    <div class="col-6 col-lg-2"><%= f.input :countries, as: :array %></div>
    <div class="col-6 col-lg-2"><%= f.input :directors, as: :array %></div>
    <div class="col-6 col-lg-2"><%= f.input :actors, as: :array %></div>
  </div>
<% end %>

app/views/admin/movies/edit.html.erb
<% content_for(:active_tab) { 'movies' } %>

<%= render 'form' %>

app/views/admin/movies/index.html.erb
<% content_for(:active_tab) { 'movies' } %>
<h2 class="fs-3 my-4">Admin Movie Panel</h2>
<h3 class="fs-5 my-4">Our movies: </h3>

<div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-3">
  <% @movies.each do |movie| %>
    <%= render 'card', movie: movie %>
  <% end %>
</div>

app/views/admin/movies/new.html.erb
<% content_for(:active_tab) { 'movies' } %>

<h2 class="fs-3 my-4">Admin Movie Panel</h2>

<ul data-controller="movie-tabs" class="nav nav-tabs mb-4" id="movieTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link <%= 'active' if cookies[:active_movie_tab].blank? || cookies[:active_movie_tab] == 'Add Manually' %>"
            id="new-movie-tab"
            data-action="click->movie-tabs#setLastActiveTab"
            data-bs-toggle="tab" data-bs-target="#new-movie-tab-pane"
            type="button" role="tab"
            aria-controls="new-movie-tab-pane" aria-selected="true">
      Add Manually
    </button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%= 'active' if cookies[:active_movie_tab] == 'Now Playing' %>"
            id="now-playing-tab"
            data-action="click->movie-tabs#setLastActiveTab"
            data-bs-toggle="tab" data-bs-target="#now-playing-tab-pane"
            type="button" role="tab"
            aria-controls="now-playing-tab-pane" aria-selected="false">
      Now Playing
    </button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%= 'active' if cookies[:active_movie_tab] == 'Upcoming' %>"
            id="upcoming-tab"
            data-action="click->movie-tabs#setLastActiveTab"
            data-bs-toggle="tab" data-bs-target="#upcoming-tab-pane"
            type="button" role="tab"
            aria-controls="upcoming-tab-pane" aria-selected="false">
      Upcoming
    </button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%= 'active' if cookies[:active_movie_tab] == 'Search' %>"
            id="search-tab"
            data-action="click->movie-tabs#setLastActiveTab"
            data-bs-toggle="tab" data-bs-target="#search-tab-pane"
            type="button" role="tab"
            aria-controls="search-tab-pane" aria-selected="false">
      Search
    </button>
  </li>
</ul>
<div class="tab-content" id="movieTabContent">
  <div class="tab-pane fade <%= 'show active' if cookies[:active_movie_tab].blank? || cookies[:active_movie_tab] == 'Add Manually' %>"
       id="new-movie-tab-pane" role="tabpanel" aria-labelledby="new-movie-tab" tabindex="0">
    <%= render 'form' %>
  </div>
  <div class="tab-pane fade <%= 'show active' if cookies[:active_movie_tab] == 'Now Playing' %>"
       id="now-playing-tab-pane" role="tabpanel" aria-labelledby="now-playing-tab" tabindex="0">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-3">
      <% @now_playing_list.each do |movie| %>
        <%= render 'card', movie: movie %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade <%= 'show active' if cookies[:active_movie_tab] == 'Upcoming' %>"
       id="upcoming-tab-pane" role="tabpanel" aria-labelledby="upcoming-tab" tabindex="0">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-3">
      <% @upcoming_list.each do |movie| %>
        <%= render 'card', movie: movie %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade <%= 'show active' if cookies[:active_movie_tab] == 'Search' %>"
       id="search-tab-pane" role="tabpanel" aria-labelledby="search-tab" tabindex="0">
    <%= form_with url: search_admin_movies_path do |f| %>
      <div class="row d-flex justify-content-center">
        <div class="col-6">
          <div class="input-group mb-3">
            <%= f.text_field :query, class: 'form-control' %>
          </div>
        </div>
        <div class="col-2">
          <%= f.submit 'Search', class: 'btn btn-dark' %>
        </div>
      </div>
    <% end %>
    <div id="search_list">

    </div>
  </div>
</div>

app/views/admin/movies/search.turbo_stream.erb
<%= turbo_stream.replace 'search_list' do %>
  <div id="search_list">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-3">
      <% @search_list.each do |movie| %>
        <%= render 'card', movie: movie %>
      <% end %>
    </div>
  </div>
<% end %>