config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "movie_sessions#index"

  get 'my_tickets', to: 'users#tickets'
  post 'webhooks', to: 'webhooks#create'

  resources :movie_sessions do
    get :swap, on: :member
    post :payment, on: :member
  end

  namespace :admin do
    resources :movies do
      post :search, on: :collection
      post 'create_with_tmdb/:external_id', on: :collection, as: :create_with_tmdb, action: :create_with_tmdb
    end

    resources :users, only: %i[index update], path: :staff do
      post 'add', on: :collection
    end

    resources :halls, except: %i[show new] do
      post :build_chart, on: :collection
    end

    resources :sessions, only: %i[index create destroy update] do
      get :tickets, on: :member
      post :book, on: :member
    end
  end
end

app/models/hall.rb
class Hall < ApplicationRecord
  has_many :sessions, dependent: :nullify

  validates :name, :scheme, presence: true

  before_destroy :have_scheduled_session, prepend: true do
    throw(:abort) if errors.present?
  end

  private

  def have_scheduled_session
    errors.add(:base, 'The hall cannot be deleted when there are scheduled sessions') if sessions.available.any?
  end
end

app/controllers/admin/halls_controller.rb
module Admin
  class HallsController < Admin::BaseController
    before_action -> { authorize(:hall) }
    before_action :load_halls, except: :build_chart
    before_action :load_hall, only: %i[update destroy]

    def index
      @hall = Hall.new
    end

    def create
      @hall = Hall.new(hall_params)
      if @hall.save
        flash.now[:success] = 'The hall has been created.'
        @hall = Hall.new
        render :index, status: :created
      else
        flash.now[:danger] = @hall.errors.full_messages.join('. ')
        render :index, status: :unprocessable_entity
      end
    end

    def update
      if @hall.update(hall_params)
        flash.now[:success] = "The #{@hall.name} hall has been updated."
        @hall = Hall.new
        render :index, status: :see_other
      else
        flash.now[:danger] = @hall.errors.full_messages.join('. ')
        @hall = Hall.new
        render :index, status: :unprocessable_entity
      end
    end

    def build_chart
      @hall = params[:hall]
    end

    def destroy
      if @hall.destroy
        flash.now[:success] = 'Hall successfully deleted.'
      else
        flash.now[:danger] = @hall.errors.full_messages.join('. ')
      end
      @hall = Hall.new
      render :index, status: :see_other
    end

    private

    def hall_params
      seats_scheme = params.dig(:hall, :scheme, :seats)
      params[:hall][:scheme][:seats] = JSON.parse(seats_scheme) if seats_scheme
      params.require(:hall).permit(:name, scheme: {})
    end

    def load_halls
      @halls = Hall.all
    end

    def load_hall
      @hall = Hall.find(params[:id])
    end
  end
end

app/views/admin/halls/_modal_form.html.erb
<div class="modal fade" id="<%= "#{id}Modal" %>" tabindex="-1"
     aria-labelledby="<%= "#{id}ModalLabel" %>" aria-hidden="true">
  <div class="modal-dialog" style="min-width: 50%;">
    <div class="modal-content" data-controller="seats">
      <div class="modal-header">
        <h3 class="modal-title fs-5"><%= title %></h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for hall, url: hall.new_record? ? admin_halls_path : admin_hall_path(hall.id) do |f| %>
        <div class="modal-body">
          <%= f.input :name, wrapper: :horizontal_form, value: nil %>
          <div class="row">
            <div class="col-sm-3 col-form-label">Size <abbr title="required">*</abbr></div>
            <div class="col-9 col-lg-3">
              <div class="input-group">
                <%= text_field_tag 'hall[scheme][rows_count]', f.object&.scheme['rows_count'],
                                   { data: { action: 'input->seats#buildSeats', seats_target: 'rowsCount' }, class: 'form-control' } %>
                <%= text_field_tag 'hall[scheme][columns_count]', f.object&.scheme['columns_count'],
                                   { data: { action: 'input->seats#buildSeats', seats_target: 'columnsCount' }, class: 'form-control' } %>
              </div>
            </div>
          </div>
          <%= hidden_field_tag 'ident_for_js', hall.id, data: { seats_target: 'hallId' } %>
          <%= render 'seating_chart', hall: hall %>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, class: 'btn-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/halls/_seating_chart.html.erb
<div class="mt-3" id="<%= "seating_chart#{hall['id']}" %>">
  <% if !hall['scheme']['rows_count'].to_i.zero? && !hall['scheme']['columns_count'].to_i.zero? %>
    <div class="row">
      <div class="col-sm-3">
        <label>Seats:</label>
      </div>
      <div class="col-sm-9 d-flex">
        <div class="border rounded-1 scroll-menu p-1">
          <% hall['scheme']['seats'].values.each.with_index(1) do |row, row_index| %>
            <ul class="d-flex showcase m-0 p-0">
              <% row.each.with_index do |seat, i| %>
                <li>
                  <div class="seat <%= 'space' unless seat %>"
                       data-row="<%= row_index %>"
                       data-column="<%= i %>"
                       data-action="click->seats#changeSeat">
                  </div>
                </li>
              <% end %>
            </ul>
          <% end %>
          <%= hidden_field_tag 'hall[scheme][seats]', hall['scheme']['seats'].to_json, data: { seats_target: 'seatsScheme' } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/halls/build_chart.turbo_stream.erb
<%= turbo_stream.replace "seating_chart#{@hall['id']}" do %>
  <%= render 'seating_chart', hall: @hall %>
<% end %>

app/views/admin/halls/index.html.erb
<% content_for(:active_tab) { 'halls' } %>

<div class="row">
  <div class="col-6"><h2 class="fs-3">Halls</h2></div>
  <% if policy(:hall).create? %>
    <div class="col-6 d-flex flex-row-reverse">
      <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="<%= "#newHallModal" %>">
        <%= t('admin.halls.actions.create') %>
      </button>
      <%= render 'modal_form', id: 'newHall', title: 'New hall', hall: @hall %>
    </div>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <% if policy(:hall).update? || policy(:hall).destroy? %>
      <th scope="col">Actions</th>
    <% end %>
  </tr>
  </thead>
  <tbody class="table-group-divider">
  <% @halls.each do |hall| %>
    <tr>
      <td><%= hall.name %></td>
      <td>
        <%= link_to 'Edit', '#', data: { bs_toggle: 'modal', bs_target: "#editHall_#{hall.id}Modal" } if policy(:hall).update? %>
        <%= link_to 'Destroy', admin_hall_path(hall), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } if policy(:hall).destroy? %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<% @halls.each do |hall| %>
  <%= render 'modal_form', id: "editHall_#{hall.id}", title: "Edit #{hall.name} hall", hall: hall %>
<% end %>