config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "movie_sessions#index"

  get 'my_tickets', to: 'users#tickets'
  post 'webhooks', to: 'webhooks#create'

  resources :movie_sessions do
    get :swap, on: :member
    post :payment, on: :member
  end

  namespace :admin do
    resources :movies do
      post :search, on: :collection
      post 'create_with_tmdb/:external_id', on: :collection, as: :create_with_tmdb, action: :create_with_tmdb
    end

    resources :users, only: %i[index update], path: :staff do
      post 'add', on: :collection
    end

    resources :halls, except: %i[show new] do
      post :build_chart, on: :collection
    end

    resources :sessions, only: %i[index create destroy update] do
      get :tickets, on: :member
      post :book, on: :member
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  PERMISSION_LEVELS = %w[
    manage_movies
    manage_halls
    manage_sessions
    ticket_sales
  ]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tickets

  enum role: %i[user admin superadmin]

  def stripe_customer
    stripe_customer_id ? Stripe::Customer.retrieve(stripe_customer_id) : create_stripe_customer
  end

  private

  def create_stripe_customer
    stripe_customer = Stripe::Customer.create(email: email)
    update(stripe_customer_id: stripe_customer.id)
    stripe_customer
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    before_action -> { authorize(:user) }
    before_action :load_users

    def index; end

    def update
      if params[:commit] == t('admin.users.actions.downgrade')
        user.update(role: :user, permissions: [])
        flash.now[:success] = "#{user.email} has been downgraded to user!"
      else
        user.update(params[:user].present? ? user_params : { permissions: [] })
          params[:commit] == t('admin.users.actions.update') ? "Permissions for #{user.email} updated!" :
                                                               "#{user.email} has been added to the team!"
      end
      @user = User.new
      render :index, status: :see_other
    end

    def add
      if user.present?
        if user.user?
          user.update(user_params)
          flash.now[:success] = "#{params[:user][:email]} has been added to the team!"
        else
          flash.now[:danger] = "User with this email already admin!"
        end
        @user = User.new
      else
        flash.now[:danger] = "User with this email does not exist"
      end
      render :index, status: :see_other
    end

    private

    def user
      @user ||= params[:id] ? User.find(params[:id]) : User.find_by(email: params[:user][:email])
    end

    def load_users
      @users = User.where.not(role: :user)
    end

    def user_params
      params.require(:user).permit(:role, permissions: [])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def tickets
    @tickets = current_user.tickets.includes(session: [:movie, :hall]).where(session_id: Session.available.pluck(:id))
  end
end

app/views/admin/users/_add_modal.html.erb
<div class="modal fade" id="<%= "addModal" %>" tabindex="-1"
     aria-labelledby="<%= "addModalLabel" %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title fs-5" id="addModalLabel">New teammate</h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for :user, url: add_admin_users_path do |f| %>
        <div class="modal-body">
          <%= f.input :email, wrapper: :horizontal_form, value: nil  %>
          <%= f.hidden_field :role, value: :admin %>
          <%= render 'permissions_list' %>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, t('admin.users.actions.add'), class: 'btn-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/_permissions_list.html.erb
<div class="form-switch check_boxes optional user_permissions">
  <label class="col-sm-3 col-form-label pt-0 check_boxes optional">Permissions</label>
  <div class="col-sm-9">
    <% User::PERMISSION_LEVELS.each do |x| %>
      <div class="form-check">
        <label>
          <input class="form-check-input check_boxes optional" role="switch" type="checkbox"
                 value="<%= x %>" name="user[permissions][]" id="<%= "user_permissions_#{x}" %>"
                 <%= 'checked' if local_assigns.has_key?(:user) && user.permissions.include?(x) %>>
          <%= t("users.permissions.#{x}") %>
        </label>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/_permissions_modal.html.erb
<div class="modal fade" id="<%= "permissionsModal#{user.id}" %>" tabindex="-1"
     aria-labelledby="<%= "permissionsModal#{user.id}Label" %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title fs-5" id="<%= "permissionsModal#{user.id}Label" %>">Permissions for <%= user.email %></h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for user, url: admin_user_path(user)  do |f| %>
        <div class="modal-body">
          <%= render 'permissions_list', user: user %>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, t('admin.users.actions.downgrade'), class: 'btn-link',
                       data: { turbo_confirm: t('admin.users.actions.downgrade_confirmation', email: user.email) } %>
          <%= f.button :submit, t('admin.users.actions.update'), class: 'btn-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% content_for(:active_tab) { 'staff' } %>
<div class="row">
  <div class="col-6"><h2 class="fs-3">Staff</h2></div>
  <div class="col-6 d-flex flex-row-reverse">
    <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="<%= "#addModal" %>">
      <%= t('admin.users.actions.add') %>
    </button>
    <%= render 'add_modal' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td>
          <% if user.admin? %>
            <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="<%= "#permissionsModal#{user.id}" %>">
              Permissions
            </button>
            <%= render 'permissions_modal', user: user %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>