config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "movie_sessions#index"

  get 'my_tickets', to: 'users#tickets'
  post 'webhooks', to: 'webhooks#create'

  resources :movie_sessions do
    get :swap, on: :member
    post :payment, on: :member
  end

  namespace :admin do
    resources :movies do
      post :search, on: :collection
      post 'create_with_tmdb/:external_id', on: :collection, as: :create_with_tmdb, action: :create_with_tmdb
    end

    resources :users, only: %i[index update], path: :staff do
      post 'add', on: :collection
    end

    resources :halls, except: %i[show new] do
      post :build_chart, on: :collection
    end

    resources :sessions, only: %i[index create destroy update] do
      get :tickets, on: :member
      post :book, on: :member
    end
  end
end

app/views/layouts/partials/_admin_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary justify-content-md-center mb-4">
  <div class="container">
    <%= link_to 'Cinema', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <% if policy(:movie).new? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle <%= 'active' if content_for(:active_tab) == 'movies' %>"
               href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Movies
            </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Our movies', admin_movies_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Add new one', new_admin_movie_path, class: 'dropdown-item' %></li>
              </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Movies', admin_movies_path, class: "nav-link #{'active' if content_for(:active_tab) == 'movies'}" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Sessions', admin_sessions_path, class: "nav-link #{'active' if content_for(:active_tab) == 'sessions'}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Halls', admin_halls_path, class: "nav-link #{'active' if content_for(:active_tab) == 'halls'}" %>
        </li>
        <% if current_user.superadmin? %>
          <li class="nav-item">
            <%= link_to 'Staff', admin_users_path, class: "nav-link #{'active' if content_for(:active_tab) == 'staff'}" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/partials/_flashes.html.erb
<div id="flashes">
  <% flash.select { |k, v| k.to_s.in?(%w(success danger)) && v.present? }.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg justify-content-md-center mb-4">
  <div class="container">
    <%= link_to 'Cinema', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Sessions', root_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Tickets', my_tickets_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <% if !current_user.user? %>
            <li class="nav-item">
              <%= link_to 'Admin panel', admin_movies_path, class: 'nav-link' %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>